namespace Customisation
{
    public enum ItemType
    {
        All_Elements,
        No_Elements,
        Eyebrows,
        FacialHair,
        Torso,
        Arm_Upper_Right,
        Arm_Upper_Left,
        Arm_Lower_Right,
        Arm_Lower_Left,
        Hand_Right,
        Hand_Left,
        Hips,
        Leg_Right,
        Leg_Left,
        Hair,
        Head_Attachment,
        Base_Hair,
        No_FacialHair,
        No_Hair,
        Back_Attachment,
        Shoulder_Attachment_Right,
        Shoulder_Attachment_Left,
        Elbow_Attachment_Right,
        Elbow_Attachment_Left,
        Hips_Attachment,
        Knee_Attachement_Right,
        Knee_Attachement_Left,
        Elf_Ear,
    }
}